# External services
spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DB_REFRESH:update}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://dbint:dbint@afrinic0-bvezf.gcp.mongodb.net/test?retryWrites=true&w=majority}
#      uri: ${MONGODB_URI:mongodb://localhost:27017/test}
#      uri: mongodb+srv://dbint:dbint@afrinic0-bvezf.gcp.mongodb.net/test?retryWrites=true&w=majority
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

